### ISSUE TITLE
5.5/Mavericks Server/MailParse

### ISSUE THREAD

**Issue by tshaw** [liip/php-osx#100]
Installed mailparse just like I did for 5.3 but no joy here. I get 

PHP Fatal error:  Call to undefined function mailparse_msg_parse_file() in /Groups/surbl/winnow/MimeMailParser.class.php on line 94

My mailparse build which appears to work like it did under 5.3:

$ sudo pecl install mailparse
Password:
downloading mailparse-2.1.6.tgz ...
Starting to download mailparse-2.1.6.tgz (36,538 bytes)
..........done: 36,538 bytes
9 source files, building
WARNING: php_bin /usr/local/php5/bin/php appears to have a suffix 5/bin/php, but config variable php_suffix does not match
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6
running: /private/tmp/pear/temp/mailparse/configure
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for a sed that does not truncate output... /usr/bin/sed
checking for cc... cc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.out
checking for suffix of executables...
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether cc accepts -g... yes
checking for cc option to accept ISO C89... none needed
checking how to run the C preprocessor... cc -E
checking for icc... no
checking for suncc... no
checking whether cc understands -c and -o together... yes
checking for system library directory... lib
checking if compiler supports -R... no
checking if compiler supports -Wl,-rpath,... yes
checking build system type... x86_64-apple-darwin13.0.0
checking host system type... x86_64-apple-darwin13.0.0
checking target system type... x86_64-apple-darwin13.0.0
checking for PHP prefix... /usr/local/php5
checking for PHP includes... -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib
checking for PHP extension directory... /usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212
checking for PHP installed headers prefix... /usr/local/php5/include/php
checking if debug is enabled... no
checking if zts is enabled... no
checking for re2c... no
configure: WARNING: You will need re2c 0.13.4 or later if you want to regenerate PHP parsers.
checking for gawk... no
checking for nawk... no
checking for awk... awk
checking if awk is broken... no
checking whether to enable mailparse support... yes, shared
checking for ld used by cc... /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld
checking if the linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) is GNU ld... no
checking for /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld option to reload object files... -r
checking for BSD-compatible nm... /usr/bin/nm
checking whether ln -s works... yes
checking how to recognize dependent libraries... pass_all
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking dlfcn.h usability... yes
checking dlfcn.h presence... yes
checking for dlfcn.h... yes
checking the maximum length of command line arguments... 196608
checking command to parse /usr/bin/nm output from cc object... ok
checking for objdir... .libs
checking for ar... ar
checking for ranlib... ranlib
checking for strip... strip
checking for dsymutil... dsymutil
checking for nmedit... nmedit
checking for -single_module linker flag... yes
checking for -exported_symbols_list linker flag... yes
checking if cc supports -fno-rtti -fno-exceptions... yes
checking for cc option to produce PIC... -fno-common
checking if cc PIC flag -fno-common works... yes
checking if cc static flag -static works... no
checking if cc supports -c -o file.o... yes
checking whether the cc linker (/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/ld) supports shared libraries... yes
checking dynamic linker characteristics... darwin13.0.0 dyld
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... no

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/mailparse/mailparse.c -o mailparse.lo
mkdir .libs
cc -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/mailparse/mailparse.c  -fno-common -DPIC -o .libs/mailparse.o
/private/tmp/pear/temp/mailparse/mailparse.c:1389:78: warning: passing 'long _' to parameter of type 'unsigned long *' converts between pointers to integer types with different sign [-Wpointer-sign]
               zend_hash_get_current_key_ex(Z_ARRVAL_P(attr->attributes), &key, &key_len, &num_index, 0, &pos);
                                                                                          ^~~~~~~~~~
/usr/local/php5/include/php/Zend/zend_hash.h:178:107: note: passing argument to parameter 'num_index' here
ZEND_API int zend_hash_get_current_key_ex(const HashTable *ht, char *_str_index, uint *str_length, ulong *num_index, zend_bool duplicate, HashPosition *pos);
                                                                                                         ^
/private/tmp/pear/temp/mailparse/mailparse.c:1394:48: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
     spprintf(&newkey, 0, "%s%d", attrprefix, num_index);
                             ~~               ^~~~~~~~~
                             %ld
2 warnings generated.
/bin/sh /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/mailparse/php_mailparse_mime.c -o php_mailparse_mime.lo
cc -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/mailparse/php_mailparse_mime.c  -fno-common -DPIC -o .libs/php_mailparse_mime.o
/bin/sh /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/mailparse/php_mailparse_rfc822.c -o php_mailparse_rfc822.lo
cc -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/mailparse/php_mailparse_rfc822.c  -fno-common -DPIC -o .libs/php_mailparse_rfc822.o
/bin/sh /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/libtool --mode=link cc -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/usr/local/php5/include/php -I/usr/local/php5/include/php/main -I/usr/local/php5/include/php/TSRM -I/usr/local/php5/include/php/Zend -I/usr/local/php5/include/php/ext -I/usr/local/php5/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -o mailparse.la -export-dynamic -avoid-version -prefer-pic -module -rpath /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/modules  mailparse.lo php_mailparse_mime.lo php_mailparse_rfc822.lo
cc ${wl}-flat_namespace ${wl}-undefined ${wl}suppress -o .libs/mailparse.so -bundle  .libs/mailparse.o .libs/php_mailparse_mime.o .libs/php_mailparse_rfc822.o
dsymutil .libs/mailparse.so || :
creating mailparse.la
(cd .libs && rm -f mailparse.la && ln -s ../mailparse.la mailparse.la)
/bin/sh /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/libtool --mode=install cp ./mailparse.la /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/modules
cp ./.libs/mailparse.so /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/modules/mailparse.so
## cp ./.libs/mailparse.lai /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/modules/mailparse.la

Libraries have been installed in:
  /private/tmp/pear/temp/pear-build-roothVN2yO/mailparse-2.1.6/modules

If you ever happen to want to link against installed libraries
in a given directory, LIBDIR, you must either use libtool, and
specify the full pathname of the library, or use the `-LLIBDIR'
flag during linking and do at least one of the following:
- add LIBDIR to the `DYLD_LIBRARY_PATH' environment variable
  during execution

See any operating system documentation about shared libraries for
## more information, such as the ld(1) and ld.so(8) manual pages.

Build complete.
Don't forget to run 'make test'.

running: make INSTALL_ROOT="/private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6" install
Installing shared extensions:     /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/
running: find "/private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6" | xargs ls -dils
8396610   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6
8396974   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr
8396975   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local
8396976   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5
8396977   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib
8396978   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib/php
8396979   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib/php/extensions
8396980   0 drwxr-xr-x  3 root  wheel    102 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212
8396981 128 -rwxr-xr-x  1 root  wheel  63632 Dec 24 08:16 /private/tmp/pear/temp/pear-build-roothVN2yO/install-mailparse-2.1.6/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/mailparse.so

Build process completed successfully
Installing '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20121212/mailparse.so'
install ok: channel://pecl.php.net/mailparse-2.1.6
configuration option "php_ini" is not set to php.ini location
You should add "extension=mailparse.so" to php.ini

**Comment by DavidTheBugWriter** [comment]
I'm having this same issue trying to build mailparse for php 5.5.18. My OSX XCode tools are up to date.

"
Davids-MBP:Downloads david$ pecl install mailparse
WARNING: channel "pecl.php.net" has updated its protocols, use "pecl channel-update pecl.php.net" to update
downloading mailparse-2.1.6.tgz ...
Starting to download mailparse-2.1.6.tgz (36,538 bytes)
..........done: 36,538 bytes
9 source files, building
running: phpize
Configuring for:
PHP Api Version:         20121113
Zend Module Api No:      20121212
Zend Extension Api No:   220121212
building in /private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6
running: /private/tmp/pear/temp/mailparse/configure
....

creating libtool
appending configuration tag "CXX" to libtool
configure: creating ./config.status
config.status: creating config.h
running: make
/bin/sh /private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6/libtool --mode=compile cc  -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/Applications/MAMP/bin/php/php5.5.18/include/php -I/Applications/MAMP/bin/php/php5.5.18/include/php/main -I/Applications/MAMP/bin/php/php5.5.18/include/php/TSRM -I/Applications/MAMP/bin/php/php5.5.18/include/php/Zend -I/Applications/MAMP/bin/php/php5.5.18/include/php/ext -I/Applications/MAMP/bin/php/php5.5.18/include/php/ext/date/lib  -DHAVE_CONFIG_H  -g -O2   -c /private/tmp/pear/temp/mailparse/mailparse.c -o mailparse.lo
mkdir .libs
 cc -I. -I/private/tmp/pear/temp/mailparse -DPHP_ATOM_INC -I/private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6/include -I/private/tmp/pear/temp/pear-build-davidJjvGlF/mailparse-2.1.6/main -I/private/tmp/pear/temp/mailparse -I/Applications/MAMP/bin/php/php5.5.18/include/php -I/Applications/MAMP/bin/php/php5.5.18/include/php/main -I/Applications/MAMP/bin/php/php5.5.18/include/php/TSRM -I/Applications/MAMP/bin/php/php5.5.18/include/php/Zend -I/Applications/MAMP/bin/php/php5.5.18/include/php/ext -I/Applications/MAMP/bin/php/php5.5.18/include/php/ext/date/lib -DHAVE_CONFIG_H -g -O2 -c /private/tmp/pear/temp/mailparse/mailparse.c  -fno-common -DPIC -o .libs/mailparse.o
/private/tmp/pear/temp/mailparse/mailparse.c:34:2: error: The mailparse extension requires the mbstring extension!
#error The mailparse extension requires the mbstring extension!
 ^
/private/tmp/pear/temp/mailparse/mailparse.c:1389:78: warning: passing 'long *' to parameter of type 'unsigned long *' converts between pointers to integer types with different sign [-Wpointer-sign]
                zend_hash_get_current_key_ex(Z_ARRVAL_P(attr->attributes), &key, &key_len, &num_index, 0, &pos);
                                                                                           ^~~~~~~~~~
/Applications/MAMP/bin/php/php5.5.18/include/php/Zend/zend_hash.h:179:107: note: passing argument to parameter 'num_index' here
ZEND_API int zend_hash_get_current_key_ex(const HashTable *ht, char **str_index, uint *str_length, ulong *num_index, zend_bool duplicate, HashPosition *pos);
                                                                                                          ^
/private/tmp/pear/temp/mailparse/mailparse.c:1394:48: warning: format specifies type 'int' but the argument has type 'long' [-Wformat]
      spprintf(&newkey, 0, "%s%d", attrprefix, num_index);
                              ~~               ^~~~~~~~~
                              %ld
2 warnings and 1 error generated.
make: *** [mailparse.lo] Error 1
ERROR: `make' failed

"
