### ISSUE TITLE
Version 5.5.6 CLI very slow

### ISSUE THREAD

**Issue by huckeduster** [liip/php-osx#102]
This could almost be a copy of issue #82. Details:

PHP version: 5.5.6
Mac OS X: 10.8.5

Problem:

> Andre@macgyver~: time php -v
> PHP 5.5.6 (cli) (built: Nov 14 2013 12:34:38)
> Copyright (c) 1997-2013 The PHP Group
> Zend Engine v2.5.0, Copyright (c) 1998-2013 Zend Technologies
>    with Xdebug v2.2.2, Copyright (c) 2002-2013, by Derick Rethans
> 
> real  0m5.052s
> user  0m0.033s
> sys   0m0.015s

I deactivated all extensions in /usr/local/php5/php.d, but still get this 5 seconds delay. Had this some time ago (probably with MAMP) and the solution was to deactivate the IMAP extension. But there is no IMAP extension to deactivate as far as I can see.

I don't know whether this is a cli only problem, cause I don't use builtin apache server.

**Comment by mlebkowski** [comment]
Adding your hostname to `/etc/hosts` worked well for me:

```
::1             marakei.local
127.0.0.1       marakei.local
```
http://serverfault.com/questions/586141/php-cli-with-imap-5-second-startup-delay

**Comment by innoscience** [comment]
Can confirm that the solution indicated by @mlebkowski worked, your machine's current hostname should be added to the hosts file. You can also append to the existing entries:

     127.0.0.1	localhost iMac.local
     ::1        localhost iMac.local

**Comment by benjamitauler** [comment]
Works for me too! :)

**Comment by tamhv** [comment]
Thanks @innoscience it works!

**Comment by MladenJanjetovic** [comment]
To find you machine's local hostname check this:
`On your Mac, choose Apple menu  > System Preferences, then click Sharing`
