### ISSUE TITLE
Syntax error while running Python 3.*

### ISSUE THREAD

**Issue by ben-tazulev** [liip/php-osx#114]
Hi,

On a 10.8 Mountain Lion system running Python 3.3 by default, the install process throw a syntax error :

<pre>
/usr/local/packager/packager.py install 5.5-10.8-frontenddev
  File "/usr/local/packager/packager.py", line 38
    print "ERROR: Option %s is not valid for command %s\n" % (opt[0], command)
                                                         ^
SyntaxError: invalid syntax
</pre>

Everything went fine while using a Python 2.\* version : 

<pre>
/usr/bin/python2.7 /usr/local/packager/packager.py install 5.5-10.8-frontenddev
</pre>

Maybe you should check the default Python version used in order to prevent user for incompatibility issue ?

Great script anyway; thanks :)

**Comment by CraftThatBlock** [comment]
Added a little part as said above. Not sure if would actually work though.
https://github.com/liip/packager/pull/1

**Comment by chregu** [comment]
merged your PR, thanks. also hopefully solved with the latest install script, where we explicitly take the system python 2.x binaries
