### ISSUE TITLE
curl_exec: "Failed initialization"

### ISSUE THREAD

**Issue by rossmcf** [liip/php-osx#144]
Hi,

I've recently upgraded to Yosemite and installed the 5.5 php-osx package.

When making curl_exec requests, I'm getting a "Failed initialization" error. I've checked the URL from my machine, and it's fine.

All `curl_setopt()` calls are returning `true`. The Failed Initialization error is only reported after the `curl_exec()` call.

`php -v` shows:

```
PHP 5.5.18 (cli) (built: Oct 20 2014 17:14:13) 
```

From `php -i`:

```
cURL support => enabled
cURL Information => 7.37.1
```

I'd appreciate any help you could offer.

Thanks,
Ross

**Comment by chregu** [comment]
No feedback for a longtime. closing
