### ISSUE TITLE
need odbc

### ISSUE THREAD

**Issue by jurowi7** [liip/php-osx#146]
About a year ago your php package contained odbc.  I'm in need of it again but noticed the new package doesn't come with odbc.  What is the easiest way I can get that extension again?  I'm currently using a Mac running OS X Yosemite.

**Comment by airmoi** [comment]
+1 iODBC support would be great

**Comment by laynebay** [comment]
+1.  I also have been using your packages and they're great, but we use ODBC often and we've had to resort to using older VMs with older versions of PHP on older OS X so we can run ODBC.  I would try PDO (odbc) but also isn't available.  Any clues, I'd appreciate it. Thanks.

**Comment by homofortis** [comment]
+1 need connection to MS SQL

**Comment by robstott** [comment]
Likewise. I know its old and horrible, but we need to support some legacy stuff that uses odbc_connect all over the place. It'd be great to have it added back in.

**Comment by airmoi** [comment]
PHP dist provided by homebrew include ODBC support (unixODBC).
I've switched to it last month as i really needed it

**Comment by chregu** [comment]
It's finally included for 10.10+ builds
