### ISSUE TITLE
Install Phalcon extension

### ISSUE THREAD

**Issue by WagnerMatos** [liip/php-osx#148]
I've been trying to install Phalcon after installing PHP 5.6, but it doesn't seem to work at all and I can't find any documentation on how to make it work.

I've been trying to install it using homebrew: `brew install php56-phalcon` which seems to install but doesn't load the extension. 

Any ideas?

**Comment by chregu** [comment]
with brew it only will work, if you use PHP provided by brew. From http://docs.phalconphp.com/en/latest/reference/install.html#compilation
the following should work

```
git clone --depth=1 git://github.com/phalcon/cphalcon.git
cd cphalcon/build
sudo ./install
````

make sure `which phpize` points to `/usr/local/php5/bin/phpize`, if not adjust your PATH to include that first.

**Comment by pjezek** [comment]
It does work ;)

**Comment by WagnerMatos** [comment]
Many thanks for the reply. I've followed the steps, but it seems I don't phpsize on my machine. Would that  make sense?

**Comment by chregu** [comment]
It's in /usr/local/php5/bin/phpize (if you have installed php-osx, if you don't have installed it, then this is the wrong place ;))

If you have installed it, try setting the path to /usr/local/php5/bin with
````
export PATH=/usr/local/php5/bin:$PATH
````

**Comment by chregu** [comment]
please reopen, if this still a problem
