### ISSUE TITLE
5 second execution delay on Mac OS X 10.10 using latest PHP 5.6.6

### ISSUE THREAD

**Issue by mstnorris** [liip/php-osx#150]
I have installed the latest version of PHP on a completely clean installation of Mac OS X 10.10.2.

I only have a few other apps installed too. The default php installation is lightning fast but if I change my $PATH to include the new version of PHP (5.6.6) I get a consistent 5+ second delay before anything is executed.

```bash
PHP 5.6.6 (cli) (built: Feb 20 2015 22:47:58)
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.6.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.4-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans
```

There is a consistent 5+ second delay whenever I run even the simplest of php scripts.

Is anyone else having this issue? What other information should I provide to help resolve this?

**Comment by chregu** [comment]
It's the imap extension, see eg. this
https://github.com/liip/php-osx/issues/102#issuecomment-74635779
or this
https://github.com/liip/php-osx/issues/102#issuecomment-51686284

**Comment by akmumu** [comment]
yes, when i remove the php.d/50-extension-imap.ini , work for me
