### ISSUE TITLE
More pecl instal problems (5.6 on Yosemite)

### ISSUE THREAD

**Issue by tshaw** [liip/php-osx#151]
I checked and exported path 

export PATH=/usr/local/php5/bin:$PATH

then I tried which didn't work

# sudo pecl install mailparse
Password:
downloading mailparse-2.1.6.tgz ...
Starting to download mailparse-2.1.6.tgz (36,538 bytes)
.....done: 36,538 bytes
9 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed

So then I tried your redo on your web page with no luck:

# sudo /usr/local/php5/bin/pecl install mailparse
Password:
downloading mailparse-2.1.6.tgz ...
Starting to download mailparse-2.1.6.tgz (36,538 bytes)
..........done: 36,538 bytes
9 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed

I note that there is no $PHP_AUTOCONF defined 

Help is apprecialetd

**Comment by chregu** [comment]
I don't think we include autoconf, it's usually not needed. Can you install it with homebrew for example? And try again

**Comment by ashish-kartrocket** [comment]
I also encountered same error :(

_sudo /usr/local/php5/bin/pecl install gearman_
Password:
downloading gearman-1.1.2.tgz ...
Starting to download gearman-1.1.2.tgz (30,961 bytes)
........done: 30,961 bytes
3 source files, building
running: phpize
Configuring for:
PHP Api Version:         20131106
Zend Module Api No:      20131226
Zend Extension Api No:   220131226
Cannot find autoconf. Please check your autoconf installation and the
$PHP_AUTOCONF environment variable. Then, rerun this script.

ERROR: `phpize' failed

**Comment by chregu** [comment]
I close this issue, please do `brew install autoconf` if you want your own pecl installations. I don't plan do add that to the package
