### ISSUE TITLE
Remove and clean install

### ISSUE THREAD

**Issue by tshaw** [liip/php-osx#155]
I followed the description to uninstall changing /etc/apache2/httpd.conf and removing /usr/local/php5-*

then I went to reinstall and I get error:

Package 5.6-10.10-frontenddev is already installed at version 5.6.9-20150515-130841. You wanted to install version 5.6.9-20150515-130841.

All help is appreciated,

Tom

$ curl -s http://php-osx.liip.ch/install.sh | bash -s 5.6
****
[WARNING]
Detected OS X Yosemite 10.10. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time)
downloading http://php-osx.liip.ch/install/5.6-10.10-frontenddev-latest.dat
downloading http://php-osx.liip.ch/install/5.6-10.10/frontenddev/5.6-10.10-frontenddev-5.6.9-20150515-130841.tar.bz2

Installing package 5.6-10.10-frontenddev into root /
Package 5.6-10.10-frontenddev is already installed at version 5.6.9-20150515-130841. You wanted to install version 5.6.9-20150515-130841.

**Comment by beatjunky99** [comment]
`sudo rm -iv /usr/local/packager/registry.log` is your friend.
Or `sudo $EDITOR /usr/local/packager/registry.log` if you just want to remove a single version.

**Comment by pjezek** [comment]
Updated documentation with the reinstallation note:
http://php-osx.liip.ch/#reinstall

@beatjunky99 thanks for answering ;)
