### ISSUE TITLE
sudo /usr/local/php5/bin/pecl install pecl_http  doesn't work - no autoconf

### ISSUE THREAD

**Issue by thepurpleblob** [liip/php-osx#158]
The above (from the FAQ) doesn't work because OSX doesn't have autoconf by default.

**Comment by patrickwilliamwalker** [comment]
Once I installed autoconf, this is what the pecl install script says (trimmed):

.
.
.
/usr/local/php5/include/php/main/php_config.h:6:19: note: expanded from macro 'ZEND_API'
# define ZEND_API __attribute__ ((visibility("default")))
                  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
38 warnings and 20 errors generated.
make: *** [php_propro.lo] Error 1
ERROR: `make' failed

**Comment by chregu** [comment]
late reply.. but pecl_http is included since a long time now
