### ISSUE TITLE
php -v Version vs info.php

### ISSUE THREAD

**Issue by paullechevallier** [liip/php-osx#159]
Hi !

I am trying to upgrade my php version on my OSX Server.
I followed your great tutorial (http://php-osx.liip.ch), but I am still having an issue...

When I type php -v, is says that the version is 5.6.11. Great.
However, on the webpage info.php the actual php version is 5.4.43.

Do you know what I need to change in order to use php 5.6 ?

Thanks so much for your help.
Best regards,

Paul

![capture d ecran 2015-09-24 a jeudi24 09 15 - 17 44 27](https://cloud.githubusercontent.com/assets/14824008/10078458/1277f254-62e5-11e5-8caa-ecaef4c65ef4.png)
![capture d ecran 2015-09-24 a jeudi24 09 15 - 17 44 40](https://cloud.githubusercontent.com/assets/14824008/10078457/1277f740-62e5-11e5-8ade-d31a3dd855f3.png)
![capture d ecran 2015-09-24 a jeudi24 09 15 - 17 44 51](https://cloud.githubusercontent.com/assets/14824008/10078459/127c0a60-62e5-11e5-9b60-6e3465519b2f.png)

**Comment by GromNaN** [comment]
It looks like the system version of PHP is used Apache.
Have you tried changing it (by doing the invers of this: http://php-osx.liip.ch/#uninstall) and restart Apache.
