### ISSUE TITLE
Installation on El Capitan works with one hiccup

### ISSUE THREAD

**Issue by bbowden** [liip/php-osx#161]
Installation on 10.11.1 is now working. Initially Apache would fail to launch but that was because the /usr/local/php5 already existed with outdated files, presumably as a result of a long ago entropy installation. I deleted that folder and renamed the php5-5.6.14-20151002-085853 folder to php5.
After that everything is working.

Thanks guys for getting me out of a major problem - I needed freetype and it is not in El Capitan.

**Comment by chregu** [comment]
I close this issue. please reopen, if you think we should do something about that
