### ISSUE TITLE
Old ICU4C-Version

### ISSUE THREAD

**Issue by jostolle** [liip/php-osx#163]
I encountered some problems with the intl-extension installed with this package. It seems to use ICU4C version 4.6. I encountered a strange behaviour with this particular version of intl. It seems to display a wrong date for dates before the first Monday of a year (showing the previous year instead). 
I couldn't find out what and where exactly was the problem, so, this is just a warning.

**Comment by D1M** [comment]
Still have same issue on my Mac :( Is it possible to update ICU to the latest one?

**Comment by chregu** [comment]
That is now updated to the latest one on PHP 7.0.1, can you please test?

**Comment by D1M** [comment]
php5-7.0.1-20151219-111259 - Also old version of ICU installed:
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/4.6/
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/current
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/Makefile.inc
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/pkgdata.inc
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/4.6/Makefile.inc
Extracting usr/local/php5-7.0.1-20151219-111259/lib/icu/4.6/pkgdata.inc

**Comment by chregu** [comment]
Oops. can you please try again. Hopefully it's correct this time

**Comment by D1M** [comment]
7.0.2 - it's ok.
