### ISSUE TITLE
why "Did or could not download package: 5.3-10.10-frontenddev"

### ISSUE THREAD

**Issue by August2012** [liip/php-osx#164]
Detected OS X El Capitan 10.11. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time)
downloading http://php-osx.liip.ch/install/5.3-10.10-frontenddev-latest.dat
downloading http://php-osx.liip.ch/install/5.3-10.10/frontenddev/5.3-10.10-frontenddev-5.3.29-20141019-211753.tar.bz2

downloading http://php-osx.liip.ch/5.3-10.10-frontenddev.tar.bz2
downloading http://php-osx.liip.ch/5.3-10.10-frontenddev.tar.gz
downloading http://php-osx.liip.ch/5.3-10.10-frontenddev.tgz
Did or could not download package: 5.3-10.10-frontenddev

**Comment by chregu** [comment]
Can you try again, this works for me (maybe there was something wrong, when you tried)
