### ISSUE TITLE
Easily switch between PHP versions

### ISSUE THREAD

**Issue by noplanman** [liip/php-osx#165]
Is there a command to easily switch between PHP versions without having to re-download each package every time?

Basically what I'm looking for, is a way to download all the different versions and then have aliases to choose the version I want to use.

**Comment by pjezek** [comment]
Hi noplanman,
just download the versions you want. To switch a version: open a terminal and change to 
```
cd /usr/loca
```l.
Then remove the symlink php and add a new one with:
```
rm php && ln -s php-6.x php
```

**Comment by noplanman** [comment]
Ok I see, thanks so much for that!

**Comment by noplanman** [comment]
For anyone who's interested in this, I'm busy making a [bash script to make the php version selection really easy](https://github.com/noplanman/dotfiles/blob/master/.functions) (function name is `phpswitch`).
It checks which versions are installed and then adds a handy tab completion to help select the version.
Since I'm on OSX and haven't tested it on Linux, I don't know if it just works out of the box for Linux users (probably not).

**Usage examples**:
- `$ phpswitch` gives you a list of all php-osx versions installed on your computer.
- `$ phpswitch 54` for version **5.4.x**
- `$ phpswitch 55` for version **5.5.x**
- etc.

Next step is to add the possibility to install any php-osx version available online if it's not yet installed on your computer. That would be using the installation command described on the [official page](http://php-osx.liip.ch/#install).

I'm very new to bash scripting, so if anybody wants to suggest improvements, I'm all ears :smiley:

**Comment by chapagain** [comment]
This one is a useful shell script to switch between installed liip php versions: https://gist.github.com/andrerom/b360a1b2dbbebc6ec1861b8618d64e97
