### ISSUE TITLE
El Capitan 10.11.2 and PHP 7.0.0

### ISSUE THREAD

**Issue by MHendrich** [liip/php-osx#166]
Hello,
i have tried to install the following php version:
PHP 7.0.0-dev for OS X 10.10/10.11 uploaded at 2015-07-10
with the following code in command line:  curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0

With phpinfo() i got now the information that i have installed PHP Version 5.4.43.

How to install PHP 7?

Thanks in Advance.

Michi

**Comment by chregu** [comment]
This is fixed now, please try again
