### ISSUE TITLE
php7 RC:  need to change documentation

### ISSUE THREAD

**Issue by gaming-hacker** [liip/php-osx#167]
documentation on the webpage needs to be updated for ph5 7RC

from 
LoadModule php5_module /usr/local/php5/libphp5.so
to
LoadModule php7_module /usr/local/php5/libphp7.so

and from

IfModule php5_module
	AddType application/x-httpd-php .php
	AddType application/x-httpd-php-source .phps

	IfModule dir_module
		DirectoryIndex index.php index.html
	IfModule
/IfModule

to
IfModule php7_module
	AddType application/x-httpd-php .php
	AddType application/x-httpd-php-source .phps

	IfModule dir_module
		DirectoryIndex index.php index.html
	/IfModule
/IfModule

otherwise you get a can't find host or the php interpretor won't work.

**Comment by chregu** [comment]
Where is that documented on the webpage? The installer should now (since about half an hour) take care of that. I'm happy to adjust it, but can't find it

**Comment by gaming-hacker** [comment]
http://php-osx.liip.ch
LoadModule php5_module        libexec/apache2/libphp5.so

this i defined in httpd.conf, otherwise it won't interpret php files

IfModule php7_module
