### ISSUE TITLE
PHP 7 installs to /usr/local/php5 and /usr/local/php5-7.0.0...

### ISSUE THREAD

**Issue by stevedesmond-ca** [liip/php-osx#168]
Not sure if this was intentional to get it out right away, or if there are too many side effects as of right now, but it seems like it would be better to have it be able to live side-by-side (out-of-the-box) with 5.x installations.

Should PHP 7 install to `/usr/local/php7-7.0.0...` with a symbolic link of `/usr/local/php7`?

**Comment by chregu** [comment]
Too many ifs and thens in the installer, or in short, I was just lazy ;) But I welcome Patches for this

**Comment by gaming-hacker** [comment]
just use bash
'''
#!/usr/local/env bash
if [[ -d ${INSTALLDIR_PHP5}]] ; then
 mkdir -p ${INSTALLDIR_PHP7}
ln -s  ${INSTALLDIR_PHP7} /usr/local/php7
else
 mkdir -p ${INSTALLDIR_PHP5}
ln -s ${INSTALLDIR_PHP5} /usr/local/php5
fi'''

**Comment by clorichel** [comment]
@gaming-hacker quite sorry for pinging after months...

How exactly have you considered using your bash script :

- a patch in [install.sh](https://github.com/liip/php-osx/blob/master/install.sh) ?
- something within `packager` routines ?
- running it somewhere else after `curl -s http://php-osx.liip.ch/install.sh | bash -s 7.0` ?

It would be absolutely awesome to get OSX PHP 5.5.x version out of the box, php-osx.liip.ch 5.6.x **and** php-osx.liip.ch 7.x versions within the same computer console at the price of an `export PATH=/usr/local/php5/bin:$PATH` or `export PATH=/usr/local/php7/bin:$PATH`

_Side-note : thanks to you all guys at http://liip.ch/ for this [php-osx](https://github.com/liip/php-osx) incredibly simple and useful set of tools!_
