### ISSUE TITLE
More Sane Default for `xdebug.var_display_max_depth`?

### ISSUE THREAD

**Issue by astorm** [liip/php-osx#169]
Apologies if this is old news, or something that can only be handled upstream.  I'm not super familiar with how this project runs itself (despite being a happy user since the entropy.ch days).

Would is possible to have a saner default for the 

```
xdebug.var_display_max_depth
```

setting?  By default this ships with 

```
xdebug.var_display_max_depth = 128
```

One hundred and twenty eight levels deep for a `var_dump` seems like a lot, and it's usually enough to kill an HTTP request if I'm dumping out large and/or recursive objects in PHP frameworks like Symfony, Magento, Zend, etc.  I've found

```
    xdebug.var_display_max_depth = 3
```

to be a lot more manageable.

I realize we all can add our own value for this in 

```
 /usr/local/php5/php.d/99-liip-developer.ini
```

However, I always forget about this setting whenever I install a new/different version of the PHP package, and usually spend a day with _mysterious_ timeouts on debugging sessions until I remember this setting.

**Comment by chregu** [comment]
will be at the default 3 in the next release
