### ISSUE TITLE
Could SUHOSIN (part of Hardened PHP Project) be included in the future?

### ISSUE THREAD

**Issue by Taz-1999** [liip/php-osx#171]
I just learned about SUHOSIN, a php extension that adds more protection to php-installations. It seems really good to have if you are running sites with other peoples code on it, like Wordpress, Joomla! etc. 

Apple has started to include suhosin in their version av PHP. 

Would it be possible for future versions of php-osx to have this extension too?

https://suhosin.org/stories/index.html
http://www.hardened-php.net/

**Comment by chregu** [comment]
There are no plans to include it
