### ISSUE TITLE
Using Apple Server App - apache location

### ISSUE THREAD

**Issue by simiula** [liip/php-osx#174]
Maybe is better to add to your info page that if is installed the Apple Server App, the apache config is located here: /Library/Server/Web/Config/apache2/httpd_server_app.conf.
The line to add is : LoadModule php7_module /usr/local/php5/libphp7.so
Finally do not put the check on 'Use PHP' on WebServer Apple Server App.! bacause we did manually.
Great job!

**Comment by mo3chin3** [comment]
Yep, took me awhile to learn that one as well!  Also make sure not to delete the old LoadModule line with the built in php version.  On apache restart sometimes the OS will overwrite changes made if that line is not present.  It'll keep changes if the line is simply commented out.

**Comment by valmiki** [comment]
This one is so important, it should go in the FAQ at http://php-osx.liip.ch

**Comment by valmiki** [comment]
It seems to be necessary to add the following close to the end of /Library/Server/Web/Config/apache2/httpd_server_app.conf

<IfModule php7_module>
    AddType application/x-httpd-php .php
    AddType application/x-httpd-php-source .phps
    <IfModule dir_module>
        DirectoryIndex index.html index.php
    </IfModule>
</IfModule>

**Comment by ssuess** [comment]
So can someone verify that these installs DO work (assuming configs above are followed) on Mac OS Server?
