### ISSUE TITLE
liip PHP 5.6.17 for OS X 10.8 not working with Apache 2.4.18

### ISSUE THREAD

**Issue by aMakUzr** [liip/php-osx#176]
After compiling Apache 2.4.18 on OS X 10.8.5 and installing liip PHP 5.6.17, I get:
---
/etc/apache2/httpd.conf: Cannot load /usr/local/php5/libphp5.so into server: dlopen(/usr/local/php5/libphp5.so, 10): Symbol not found: _unixd_config\n  Referenced from: /usr/local/php5/libphp5.so\n  Expected in: /usr/local/apache2/bin/httpd\n in /usr/local/php5/libphp5.so

The paths/files are all OK, PHP works fine and Apache is fully functional, otherwise (including with also-built mod_jk).

http://httpd.apache.org/docs/2.4/developer/new_api_2_4.html indicates that the API unixd_config has been renamed to ap_unixd_config in Apache 2.4, so I'm guessing that's likely the issue.

Having no prior experience compiling either PHP or Apache, I'd be interested in any suggestions.

**Comment by chregu** [comment]
it's only meant to work with the apache version coming with OS X. You'd have to recompile php, if you want to use it with Apache 2.4.

**Comment by aMakUzr** [comment]
Thanks for responding.  That's what I figured. <sigh>

Haven't looked that the code, but _if_ libphp5.so was a lightweight skin/RPC, there could be a chance that the one for 10.10 would work (IIRC, they're using Apache 2.4) ... so the obvious questions are:
- is that likely, from your (seemingly) greater-depth knowledge?
- is there a test suite that would verify the functionality if I did try it and it seemed to work?

FYI, I did download and try running "sudo bash build-php.sh" and ran into problems.  The first problem was that that "sunsite.cnlab-switch.ch" in (lib/package/gettext.pm and iconv.pm) is not resolvable.  I changed it to mirror.switch.ch and it got through those but again ran into another one and I stopped there (it was about 5:00 AM and I'd had 'nuff).  I may resume that today or may just "bite the bullet" and build everything to /usr/local, myself.

Other 'n that, I wanted to say that it's nice that you're making all this available.  Though things in the open source world have gotten _much_ better for OS X since the last time I built all my "server stuff" (circa 2008?), I remember that building PHP has a lot of dependencies and gd, in particular, was a "bear" ... so I'm sure you're saving a lot of people a lot of time.  I'll try to find the time to publish the notes I made while compiling the latest stuff on 10.8.5 (postfix, dovecot, apache, perl, clam-av, amavisd, postgrey, openssl, etc.).

Thanks, again.

**Comment by aMakUzr** [comment]
Just to "close the loop," I ended up downloading the php source (and others) and building everything.  In a way, that's better because now (supposedly) I can update individual pieces, if required.

It's nice to see that gd (and others) are now included with php, compared to the last time I built one.

Later ...
