### ISSUE TITLE
Error installing php 5.6

### ISSUE THREAD

**Issue by gofilipa** [liip/php-osx#177]
Very new to this so please bear with me... I am trying to install 5.6 and came up with a syntax error:

AH00526: Syntax error on line 20 of /private/etc/apache2/extra/httpd-mpm.conf:
Invalid command 'LockFile', perhaps misspelled or defined by a module not included in the server configuration

What should I do?

**Comment by NicolasGraph** [comment]
+1

**Comment by chregu** [comment]
Still an issue?
