### ISSUE TITLE
Apache not working after reboot

### ISSUE THREAD

**Issue by ghost** [liip/php-osx#178]
I've already upgraded php with the one line installation, but after rebooting and try the localhost it doesn't worked.
I've tried with:

```
sudo apachectl restart
and
sudo apachectl stop & start
```

but I still without connection to server

**Comment by mo3chin3** [comment]
Could be several issues. First off what version of OS X are you using? Second are you using the server app? If you get no errors from the command line after running either of those commands I would check your firewall settings first. If it's on, turn it off, verify connectivity then turn it back on and adjust its settings accordingly. You can also check the console app, on the left side find the Apache logs. That should give you good info on what is happening.

**Comment by mo3chin3** [comment]
Was the installation working before the update?  Also what version of php did up to/from?

**Comment by AlexLeonVader** [comment]
The installation worked perfectly before the upgrade, I was in 5.5.0 and upgrade to 7.0.5

**Comment by mo3chin3** [comment]
Did you change which php.so to load in the Apache config file?

**Comment by chregu** [comment]
still a problem? What's the error?
