### ISSUE TITLE
Mavericks and 5.6 installation, cannot load php5 module

### ISSUE THREAD

**Issue by reptilex** [liip/php-osx#182]
After the install apache says:
httpd: Syntax error on line 499 of /private/etc/apache2/httpd.conf: Syntax error on line 8 of /private/etc/apache2/other/+php-osx.conf: Cannot load /usr/local/php5/libphp5.so into server: dlopen(/usr/local/php5/libphp5.so, 10): Symbol not found: _CAST_ecb_encrypt\n  Referenced from: /usr/local/php5/libphp5.so\n  Expected in: /usr/lib/libSystem.B.dylib\n in /usr/local/php5/libphp5.so

So nothing works anymore. Can it be due to the fact that I have an encrypted drive?

**Comment by chregu** [comment]
argh, yes, i can reproduce that. No it has nothing to do with an encrypted drive.

Mavericks is quite old, but yeah, we say we support it... So we maybe should also properly support it.

**Comment by chregu** [comment]
reverted the latest changes regarding openssl. Should work now again on 10.9 as well
