### ISSUE TITLE
Compile with Thread Safety Support?

### ISSUE THREAD

**Issue by tegansnyder** [liip/php-osx#185]
Is it possible to recompile PHP7 with ZTS enabled? I'd like to use [pthreads](https://github.com/krakjoe/pthreads)

I assume I could fork and edit somewhere add a line like this:

```
--enable-maintainer-zts
```

**Comment by chregu** [comment]
yes, you can try that. If you have questions with the setup, just ask

**Comment by tegansnyder** [comment]
@chregu so would that change be added somewhere like this: https://github.com/liip/build-entropy-php/blob/7_0_yosemite/lib/Package/php5.pm#L76 ?

The branch says `7_0_yosemite` but I'm on El Cap.

**Comment by chregu** [comment]
yes, add it there and yosemite is the right branch for El Cap and Sierra as well

**Comment by tegansnyder** [comment]
So if I fork that, make my own changes, I would be able to install by creating a local package of some sort? Any chance you have a quick instruction set? I appreciate your help.

**Comment by tegansnyder** [comment]
Hi @chregu any chance you help answer the above question? Thanks.
