### ISSUE TITLE
memcache and memcached so files not included with 7.x releases

### ISSUE THREAD

**Issue by jtnix** [liip/php-osx#186]
memcache and memcached so libs are missing from the recent 7.0 releases, confirmed in the 7.0.8 and 7.0.10 releases I have recently installed.

The dylib files seem to be present, but the so libs and corresponding php.d ini files are absent.

Trying to perform a pecl install memcache-3.0.8 results in the attached compile errors.

[liipphp7010memcachepeclError.txt](https://github.com/liip/php-osx/files/448004/liipphp7010memcachepeclError.txt)

Would love to get this compiled in and working - any ideas?

fwiw, pecl install of this extension works fine from our CentOS 6.8 environments using php 7.0.10

**Comment by Uplink03** [comment]
I'm a HomeBrew user and this is what I had to do:

```bash
xcode-select --install # to be able to find zlib
brew install libmemcached
brew install autoconf
sudo /usr/local/php5/bin/pecl install memcached
```

Then I added `extension=memcached.so` to /usr/local/php5/php.d/99-zzz-mysettings.ini and restarted Apache.

**Comment by chregu** [comment]
The memcached extension is now included in the 7.x builds as well

**Comment by gonenradai** [comment]
I'm experiencing a very similar result (errors during pecl install memcache) after I installed php 7.1.
phpinfo shows I have memcache, but my code is still throwing 'fatal error class not found Memcache'
