### ISSUE TITLE
Sierra Issue with LibCurl

### ISSUE THREAD

**Issue by wallenium** [liip/php-osx#187]
sudo apachectl
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/curl.so' - dlopen(/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/curl.so, 9): Library not loaded: /usr/local/php5/lib/libcurl.4.dylib
  Referenced from: /usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/curl.so
  Reason: Incompatible library version: curl.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0 in <b>Unknown</b> on line <b>0</b><br />
<br />
<b>Warning</b>:  PHP Startup: Unable to load dynamic library '/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/http.so' - dlopen(/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/http.so, 9): Library not loaded: /usr/local/php5/lib/libcurl.4.dylib
  Referenced from: /usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/http.so
  Reason: Incompatible library version: http.so requires version 9.0.0 or later, but libcurl.4.dylib provides version 7.0.0 in <b>Unknown</b> on line <b>0</b><br />
/usr/sbin/apachectl: line 92:  4668 Segmentation fault: 11  $HTTPD "$@"

**Comment by chregu** [comment]
Works fine for me on sierra for 7.0 and 7.1, that's strange, I assume you didn't recompile  the http extension by yourself?

**Comment by wallenium** [comment]
nope. Fresh upgrade ;) Deleted all php-osx files and reinstalled, not sure why the issue occurred

**Comment by chregu** [comment]
Do you have any other apache extension (apart from the standard ones) installed?
I see that OS X provides
````
	/usr/lib/libcurl.4.dylib (compatibility version 7.0.0, current version 8.0.0)
````
but we install
`````
   	/usr/local/php5/lib/libcurl.4.dylib (compatibility version 9.0.0, current version 9.0.0)
````

maybe something else  loads the system libcurl before in your case

(but Sierra has the even newer curl version, I don't get why the library versions are different):
`````
$ /usr/bin/curl --version
curl 7.49.1 (x86_64-apple-darwin16.0) libcurl/7.49.1 SecureTransport zlib/1.2.8
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile GSS-API Kerberos SPNEGO NTLM NTLM_WB SSL libz UnixSockets

$ /usr/local/php5/bin/curl --version
curl 7.47.1 (x86_64-apple-darwin14.5.0) libcurl/7.47.1 SecureTransport zlib/1.2.8 libidn/1.20 libssh2/1.4.3
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp scp sftp smb smbs smtp smtps telnet tftp
Features: IDN IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets
````

**Comment by wallenium** [comment]
Hah. Got the issue. in my httpd the default php module was active... this caused the error.

**Comment by chregu** [comment]
so i close this issue then
