### ISSUE TITLE
"Received SIGHUP or SIGTERM"

### ISSUE THREAD

**Issue by ghost** [liip/php-osx#189]
I'm looking up upgrade php from 5.5.3 to 5.6.\* however following these instructions : 
https://php-osx.liip.ch/
when I run the single line command and enter my password I get 
"Received SIGHUP or SIGTERM

Buffer written to /Users/me/.bash_profile.save.1"
which creates a file I cannot open and doesn't write anything to bash.

also, /usr/local dir does not contain php however $ which php does locate to /usr/bin/php

Can anyone help me upgrade please?

**Comment by chregu** [comment]
no idea, sorry, still happening?
