### ISSUE TITLE
curl: (35) Server aborted the SSL handshake

### ISSUE THREAD

**Issue by zhangxiaoliu** [liip/php-osx#191]
➜  /  curl https://php-osx.liip.ch/install.sh | bash -s 5.6
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:--  0:03:30 --:--:--     0curl: (35) Server aborted the SSL handshake

**Comment by hiyali** [comment]
@zhangxiaoliu http://stackoverflow.com/a/39179952

**Comment by chregu** [comment]
please reopen, if still an issue

**Comment by frodrigueza** [comment]
you have to change the wifi network you are connected to. Try using your smartphone personal hotspot
