### ISSUE TITLE
OS Version comparison error when defining system GREP_OPTIONS

### ISSUE THREAD

**Issue by matthewclower** [liip/php-osx#194]
The grep for the OS version in install.sh does not support system defined (and allowed) colors for grep, e.g.: #193 

```
14:31 [matthewcl-]: ~ $ cat ~/.bash_profile | grep GREP_OPTIONS
export GREP_OPTIONS='--color=always'
14:31 [matthewcl-]: ~ $ curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6
****
Your version of OS X (10.11) is not supported, you need at least 10.6
Stopping installation...
If you think that's wrong, try
****
curl -o install.sh -s https://php-osx.liip.ch/install.sh | bash install.sh force
****
```
The error message shown looks like a very bad comparison but it's really just because of the colors defined at the system level...

In order to support a system that has this configured the --color=never must be specified in the grep command.

**Comment by chregu** [comment]
thanks for the hint, it's fixed and soon online
