### ISSUE TITLE
Error with one liner and also doing manual steps 

### ISSUE THREAD

**Issue by dkmansion** [liip/php-osx#196]
myhostname:Downloads username$ curl -s https://php-osx.liip.ch/install.sh | bash -s 7.0
Detected OS X El Capitan 10.11. All ok.
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Password:
Start packager (may take some time)
  File "/usr/local/packager/packager.py", line 38
    print "ERROR: Option %s is not valid for command %s\n" % (opt[0], command)
                                                                                               ^
SyntaxError: invalid syntax

Any recommendation on resolving this?

**Comment by samsonasik** [comment]
happen on me too, it keep hanging on console env

**Comment by samsonasik** [comment]
the curl command is working now on my side

**Comment by doudou34** [comment]
I have the same issue... Nobody resolve it?

**Comment by chregu** [comment]
The installer used the default python binaries, which can be 3.x sometimes. We changed it now to use the system python 2.x binaries
