### ISSUE TITLE
[feature] skip install if already on system

### ISSUE THREAD

**Issue by tonivdv** [liip/php-osx#197]
Hey guys,

I'm using this install in my dotfiles, and I was wondering if it would be possible to have a check during the installation phase for currently installed packages. Currently if you run the script it will always install it, even it it already exists on the system and the version is the same.

Cheers

**Comment by chregu** [comment]
I see that it only checks after downloading the whole package and then complains about "Package 7.1-10.10-frontenddev is already installed at version 7.1.1-20170213-100732. You wanted to install version 7.1.1-20170213-100732." which of course is a little bit stupid. Not sure, when I actually can fix that

**Comment by tonivdv** [comment]
@chregu it's not urgent. But it would be an improvement and avoids unnecessary downloads from the servers :)
