### ISSUE TITLE
is it possible install php5 and php7 together ?

### ISSUE THREAD

**Issue by 016** [liip/php-osx#203]
I installed php5.6 and php7.1 with "curl -s https://php-osx.liip.ch/install.sh | bash -s 5.x".

but I got a problem with /usr/local/php5 link.

looks the two php version both loading from /usr/local/php5/php.d/*.ini

what I want is using /usr/local/php5 and /usr/local/php7, but somehow, it's not working.

right now I only have php5.6 working with /usr/local/php5, php7 is not working with /usr/local/php7, I also changed everything in /usr/local/php7/php.d/*.ini

I also found this
; All relative paths in this configuration file are relative to PHP's install
; prefix (/usr/local/php5). This prefix can be dynamically changed by using the
; '-p' argument from the command line.

can anyone show me how to config the -p argument?

thx.

and is it possible to use /usr/local/php7 for php7.x

thx again, it's really help a lots.

**Comment by SiliconMind** [comment]
Unfortunately it appears that config files paths are hardcoded in the installation scripts to `/usr/local/php5/*`. I'd love to see the option to have php5 and php7 side by side.

**Comment by sinclairday** [comment]
Maybe something like this will do the trick...

```
#!/bin/bash

# usage:
# ./switch_php.sh <version>
# ./switch_php.sh php5
# ./switch_php.sh php7

# activate php56
if [ "$1" == "php5" ]; then
   sudo rm /usr/local/php5
   sudo ln -s /usr/local/php5-5.6.14-20151002-085853 /usr/local/php5
   echo "activated php5; restart apache now"
fi

if [ "$1 == "php7" ]; then
   sudo rm /usr/local/php5
   sudo ln -s /usr/local/php5-7.1.4-20170506-100436 /usr/local/php5
   echo "activated php7; restart apache now"
fi

```

To restart apache:

`sudo apachectl restart`

**Comment by avcconti** [comment]
@sinclairday solution works fine. I added a line to restart php-fpm:

```
#!/bin/bash

#usage:
#./switch_php.sh <version>
#./switch_php.sh php5
#./switch_php.sh php7

#activate php56
if [ "$1" == "php5" ]; then
   sudo rm /usr/local/php5
   sudo ln -s /usr/local/php5-5.6.27-20161101-100213 /usr/local/php5
   sudo pkill php-fpm && sudo php-fpm
   echo "activated php5;"
fi

if [ "$1" == "php7" ]; then
   sudo rm /usr/local/php5
   sudo ln -s /usr/local/php5-7.1.8-20170817-170852 /usr/local/php5
   sudo pkill php-fpm && sudo php-fpm
   echo "activated php7;"
fi
```

Remember to give permission to the script in OSX: chmod u+x script.sh

**Comment by 016** [comment]
for more info, can use this command do the symbolic link rewrite
ln -hfs /usr/local/php5-7.2.9-20180821-074958 php5

@chregu I suggest to use php56(for php 5.6.x) and php72(for php7.2.x) to instant php5

just change one var, the problem will solve forever.

@sinclairday @avcconti  thx for your apply, it's really help.
