### ISSUE TITLE
Error in installiing

### ISSUE THREAD

**Issue by gauravr-dev** [liip/php-osx#205]
I have tried to install PHP 5.6 but it is giving error.
**Command :** curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6
**Error:**
Start packager (may take some time)
  File "/usr/local/packager/packager.py", line 38
    print "ERROR: Option %s is not valid for command %s\n" % (opt[0], command)
                                                        ^
SyntaxError: invalid syntax

**Comment by chregu** [comment]
your default python is 3.x, the installer needs 2.x. We changed the install script to use 2.x, so it should work now
