### ISSUE TITLE
Xdebug does not work. Version PHP 7.1.0 - MacOs Sierra

### ISSUE THREAD

**Issue by Vagabondtq** [liip/php-osx#206]
After install, i edit file:

> /etc/php.ini

add bottom of file:
[XDebug]
```
zend_extension=/usr/lib/php/extensions/no-debug-non-zts-20131226/xdebug.so
xdebug.remote_enable=1
xdebug.remote_handler=dbgp
xdebug.remote_mode=req
xdebug.remote_host=127.0.0.1
xdebug.remote_port=9000
xdebug.remote_autostart=1
```
i find file:  /usr/local/php5/php.d/50-extension-xdebug.ini, but does not exist. I created file and then add:

> extension=xdebug.so

I ran phpinfo(), and search xdebug. It not work

**Comment by chregu** [comment]
the latest 7.1 release does include xdebug again
