### ISSUE TITLE
Bus error: 10

### ISSUE THREAD

**Issue by black-lotus** [liip/php-osx#208]
add in 

`$ nano ~/.bash_profile`

> export PATH="/usr/local/php5/bin:$PATH"

then execute by this command

`$ source ~/.bash_profile`

when i check php version

`$ php -v`

it's getting error

> Bus error: 10

i tried to access manually

`$ /usr/local/php5/bin/php -v`

it's getting same error

> Bus error: 10

i figure it out, and i think the error because i install mongodb driver for php...
when i remove extension file

`$ sudo rm -rf 50-extension-mongodb.ini `

then check php version, it's success now...
> PHP 7.1.1 (cli) (built: Feb 13 2017 10:05:49) ( NTS )
> Copyright (c) 1997-2017 The PHP Group
> Zend Engine v3.1.0, Copyright (c) 1998-2017 Zend Technologies
>     with Zend OPcache v7.1.1, Copyright (c) 1999-2017, by Zend Technologies
>     with Xdebug v2.5.0, Copyright (c) 2002-2016, by Derick Rethans

that's weird... can anyone help me 

Thank you

**Comment by chregu** [comment]
mongodb is now included with our 7.1.1 build. Can you try if that fixes the problem?

**Comment by black-lotus** [comment]
hi @chregu thank you very much...
it's working

![screen shot 2017-05-08 at 11 00 16 am](https://cloud.githubusercontent.com/assets/3261560/25789799/9b09ef30-33dd-11e7-8500-5c66831a8755.png)
