### ISSUE TITLE
Upgrading to PHP 5.5: Apache not working

### ISSUE THREAD

**Issue by zaxxted** [liip/php-osx#210]
After upgrading from PHP 5.3.26 to 5.5, on Mac OS 10.6.8, Apache is not working.
~/.profile and ~/.bash_profile seem Ok (though I don't understand anything in console stuff)

----------------
phpinfo() returns:

PHP Version 5.5.38
Configuration File (php.ini) Path: 	/usr/local/php5/lib
Loaded Configuration File:   /usr/local/php5/lib/php.ini 
Apache/2.2.24 (Unix) DAV/2 PHP/5.5.38 mod_ssl/2.2.24 OpenSSL/0.9.8y 

----------------
php -v returns:

PHP 5.5.38 (cli) (built: Aug 31 2016 10:45:24) 
Copyright (c) 1997-2015 The PHP Group
Zend Engine v2.5.0, Copyright (c) 1998-2015 Zend Technologies
    with Zend OPcache v7.0.6-dev, Copyright (c) 1999-2015, by Zend Technologies
    with Xdebug v2.2.5, Copyright (c) 2002-2014, by Derick Rethans

----------------
sudo apachectl -k restart fails and returns:

httpd: Syntax error on line 117 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/php5/libphp5.so into server: dlopen(/usr/local/php5/libphp5.so, 10): Symbol not found: _libiconv\n  Referenced from: /usr/local/php5/lib/libintl.8.dylib\n  Expected in: /usr/lib/libiconv.2.dylib\n in /usr/local/php5/lib/libintl.8.dylib

Line 117 of private/etc/apache2/httpd.conf is of course:
LoadModule php5_module        /usr/local/php5/libphp5.so

while 116 is:
#LoadModule php5_module        libexec/apache2/libphp5.so

----------------

I searched the web for this problem but didn't find solution, only weird, long and very complicated processes...
So, thank you to help me solve this installation bug, if possible with a simple an detailed process, as I'm not familiar with this kind of installation based on console.

**Comment by chregu** [comment]
still a problem?

**Comment by zaxxted** [comment]
Yes and no...
I deleted all installed files and try again a new install, but problem is exactly the same, so I deleted once again all installed files... and running back to my old config (PHP PHP Version 5.3.26).

**Comment by Myndex** [comment]
Still an issue for anyone with 10.6.8 I think. I got it to see the Libiconv library, but now it wants to see LibGIF.

UGH. 10.6.8 on an 8 core mac pro.
