### ISSUE TITLE
php7.1 ,ERROR,

### ISSUE THREAD

**Issue by abner-xu** [liip/php-osx#211]
curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1
Detected OS X El Capitan 10.11. All ok.
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Password:
Start packager (may take some time)
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/
ERROR: pkg/info file not found in package 7.1-10.10-frontenddev

**Comment by chregu** [comment]
mmh, works for me. can you try again?
what does  https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10-frontenddev-latest.dat show for you?

**Comment by xuchengithub** [comment]
@chregu Still the same, the same error message

**Comment by chregu** [comment]
Still not working for you?

**Comment by wintersunzdx** [comment]
I met the same error on all version....

**Comment by xuchengithub** [comment]
It ok, network problem
