### ISSUE TITLE
Can not enable ODBC  

### ISSUE THREAD

**Issue by digitechinternational** [liip/php-osx#214]
This version is not compiled with  ODBC. 
I have installed on my system but  , unable to activate the ODBC support in my installation.  
I have it on  OS X 10.10   PHP ver. 7.1   , see the attached . 

My PHP info  doesnt show the ODBC section.  
Also the  ./configure doesnt show the odbc support 

Please advice
![screen shot 2017-04-23 at 1 10 12 pm](https://cloud.githubusercontent.com/assets/2314249/25315635/4dd15946-2826-11e7-93af-af23968d0d46.png)

**Comment by digitechinternational** [comment]
FYI,  I have tried different versions.

**Comment by chregu** [comment]
odbc is now inclluded in all builds for 10.10+

**Comment by digitechinternational** [comment]
I still do not get it enabled. I am on OS X Yosemite version 10.10.2 (14C109)
