### ISSUE TITLE
Installation Error php 7.1 on mac os x sierra 10.12.4

### ISSUE THREAD

**Issue by crenardy** [liip/php-osx#215]
Hi,
while trying to install php 7.1 on my mac book pro (v10.12.4), I get the following error.
Any help would be appreciated!
(I'm using Python 3.6 with anaconda)
Python 3.6.0 |Anaconda 4.3.1 (x86_64)| (default, Dec 23 2016, 13:19:00) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin

(tried it with and without sudo)
$ curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1
Detected macOS Sierra 10.12. All ok.
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time)
  File "/usr/local/packager/packager.py", line 38
    print "ERROR: Option %s is not valid for command %s\n" % (opt[0], command)
                                                         ^
SyntaxError: invalid syntax
$

Kind regards
Christian

**Comment by siritsch** [comment]
The python install scripts are written for python 2.x. You are using python 3.6, which has a different syntax. See also issue 217.

**Comment by chregu** [comment]
hopefully solved with the latest install script, where we explicitly take the system python 2.x binaries
