### ISSUE TITLE
Stop in the 2nd lines while trying to upgrade to php 7.1

### ISSUE THREAD

**Issue by ghost** [liip/php-osx#220]
Hi, 

I am trying to upgrade my php in my mac 10.12 Sierra, using this curl statement:
curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1

However, it stopped in the 2 lines:
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.1-10.10/frontenddev/7.1-10.10-frontenddev-7.1.4-20170506-100436.tar.bz2

I had to press control C to terminate the proccess... 

Would you please share some lights to me on how to resolve the problem? Thanks for your help first!

**Comment by chregu** [comment]
Did you retry? The package is about 71 MB big, so it may take some time, depending on your internetconnection. There's a ticket about that on #220

**Comment by mingtam** [comment]
Thanks and I just tried to run the same command in another network. It works now! Thanks for your help!

**Comment by danersan** [comment]
i have the same problem
my internet connection was good enough i think to download 71mb
but why it still kind of stuck in frontenddev thing?
any other idea?

**Comment by maulayyacyber** [comment]
@danersan i have same the problem :(

**Comment by tri-duong-vn** [comment]
I've met the same problem and that problem disappears after I've switched to another network.
