### ISSUE TITLE
Apcu still do not work for PHP 7.1.x

### ISSUE THREAD

**Issue by borNfreee** [liip/php-osx#222]
Hello!

Just installed the latest release (`PHP 7.1.4 for OS X 10.10-10.12 uploaded at 2017-05-06`) and `apcu` does not work.

Even it's enabled in 50-extension-apcu.ini, phpinfo() show that it is disabled and functions (e.g. called from doctrine APC cache) do not exist.

<details>

```
extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so
[APCu]
apc.enabled = on
```

</details>

**Comment by chregu** [comment]
The example from https://secure.php.net/manual/en/function.apcu-add.php works fine on my PHP 7.1.4 installations. does that also not work for you?

**Comment by borNfreee** [comment]
With fresh 7.1.4 installation, example from this links displays the following:

```php
bool(false)

bool(false)
```

`php -i | grep apc`:

```
apcu
apc.coredump_unmap => Off => Off
apc.enable_cli => Off => Off
apc.enabled => On => On
apc.entries_hint => 4096 => 4096
apc.gc_ttl => 3600 => 3600
apc.mmap_file_mask => no value => no value
apc.preload_path => no value => no value
apc.serializer => php => php
apc.shm_segments => 1 => 1
apc.shm_size => 32M => 32M
apc.slam_defense => On => On
apc.smart => 0 => 0
apc.ttl => 0 => 0
apc.use_request_time => On => On
apc.writable => /tmp => /tmp
```

`cat /usr/local/php5/php.d/50-extension-apcu.ini`:

```
extension=/usr/local/php5/lib/php/extensions/no-debug-non-zts-20160303/apcu.so
[APCu]
apc.enabled = on
```

**Comment by chregu** [comment]
is that output from the shell/cli? apc is disabled on the shell by default

**Comment by borNfreee** [comment]
Oh.. sorry and thank you for the explanation.

It works great when from the browser.
