### ISSUE TITLE
PHP 7.1 is not available for OS X < 10.10 (Incorrect Version Detected)

### ISSUE THREAD

**Issue by mikebronner** [liip/php-osx#227]
When trying to install PHP 7.1 on macOS 10.13.0-beta3 I receive the error shown in the title, so it looks like this is a version detection problem. Is there a way I can force the install, and have it ignore the version?

**Comment by mikebronner** [comment]
I just tried again, and still getting incorrect version detection with High Sierra beta 6:

>[WARNING]
>Detected macOS Unnamed 10.13. As this is quite new, there may be issues still. Your mileage may vary.
>****
>PHP 7.1 is not available for OS X < 10.10

**Comment by mikebronner** [comment]
Seems to be working now in 10.13.0-beta9: was able to install php 7.1.9 without issue. Thank you!

**Comment by chregu** [comment]
ah yeah, fixed that yesterday, forgot about the issue, thanks for closing
