### ISSUE TITLE
php 7.1 installed, but server keeps telling me I got php 5...

### ISSUE THREAD

**Issue by krrkrr** [liip/php-osx#229]
Hello...

sorry to bother you, i'm on a Mac Pro 10.11.6 with server. I've followed the tuto to install php 7.1 to the letter. In the terminal, php -v does give me that I'm on php 7.1 ...

But, when I'm trying to install, let's say, NextCloud, it keeps telling me I'm on php 5.5 (the original one included in Capitan, as far as I know) ... I've tested with other distributions I'm familiar with and I got the same anwser. I've installed php 7.1 but Server keeps using php 5.x ...

can you help me out, please ? I've probably done something wrong but after a week ... I didn't find what.

Thanks a lot.

Regards

**Comment by quwax** [comment]
Hello,
I have the same problem with MacOS10.11.6 Server and php 7.2
I was looking into the http.config and it was not changed. Then I changed it by myself to just include the entropy-php.conf file (I created a symbolic link to the original and copied it to the others folder.
After restarting apache, the log says that http is crashing?
What's the solution to this?
Thank you

**Comment by krrkrr** [comment]
Hello

As it was 6 months ago, I hope I still remember how I solved my pb (not yours, I know, but I’m no expert… so I just hope it will give you some clues)

as I wanted to upgrade to php7.1 and it seemed impossible… 

Here’s the solution for my pb:

- deactivate your php in the server app (Web Sharing) 
- install php 71 with curl
curl -s https://php-osx.liip.ch/install.sh <https://php-osx.liip.ch/install.sh> | bash -s 7.1
which install php71 in /local/

- mod the .conf file used by Apache server of macOs Server which is not the same apache server as macOs (non-server)
sudo nano /Library/Server/Web/Config/apache2/httpd_server_app.conf

look for php5_module with Ctrl+W
and it comment (add a # at the beginning)
#LoadModule php5_module libexec/apache2/libphp5.so

- add the line
LoadModule php7_module /usr/local/php5-7.1.4-20170506-100436/libphp7.so
under the one u just commented

WARNING: the path above,  /usr/local/php5-7.1.4-20170506-100436/libphp7.so , should be corrected depending on your installation, the version of the php installed, etc…

- add the handler for php7, after the block http start with iFModule php5_module
<IfModule php7_module>  
    AddType application/x-httpd-php .php  
    <FilesMatch .php$>  
        SetHandler application/x-httpd-php  
    </FilesMatch>  
    <IfModule dir_module>  
        DirectoryIndex index.php index.html  
    </IfModule>  
</IfModule>  

- save with Ctrl+O, close with Ctrl+X, reboot the whole machine (rebooting the apache server may not be enough)
- in the Web Sharing part of the server app, DON’T activate php (as it un-comments the php5 module)
- check your phpinfo (and don’t use the php -v in the terminal, it doesn’t always give the right answer)

It’s the same for the php.ini, it’s not the one you think that’s gonna be used. Check which one in phpinfo.

It’s not an answer to your pb but I hope it helps.

Krr

**Comment by quwax** [comment]
Thanks Krr 🥇 
Switching off php in the ServerApp was the trick 👍 

After that I just throwed the entropy-php.conf into the other folder
corrected the mysql socket in 99-liip-developer.ini to the current one for my installation:
pdo_mysql.default_socket = /private/var/mysql/mysql.sock
mysql.default_socket = /private/var/mysql/mysql.sock
mysqli.default_socket = /private/var/mysql/mysql.sock

I'm still having an issue with roundcube as it seams to look for imap actions for the mysql socket in the temp folder, so as a work-around I created a symbolic link in the temp folder for the moment until I can find the wrong socket path.
cheers

**Comment by quwax** [comment]
Found the culprit, the pdo and mysqli socket was also set in the php.ini file with an empty path … setting the correct path fixed it :-)

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
