### ISSUE TITLE
ICU version 56.1 could be updated to 57.1 ?

### ISSUE THREAD

**Issue by rroblsgo** [liip/php-osx#232]
Hi everyone,

I'm using PHP 7.1.4 on my Mac OS Sierra, installed with:
    curl -s https://php-osx.liip.ch/install.sh | bash -s 7.1

When I install a project Symfony 3.1.10, I get the following message:

"intl ICU version installed on your system is outdated (56.1) and does not match the ICU data bundled with Symfony (57.1).
To get the latest internationalization data upgrade the ICU system package and the intl PHP extension."

How could I upgrade intl ICU on my actual PHP configuration?.
Has anyone see it before?

Thank you so much in advance

**Comment by chregu** [comment]
I updated the packages and the use now ICU 58.1, I hope that works with symfony ;)

**Comment by rroblsgo** [comment]
I've reinstalled and it's all OK.
Thank you very much!

**Comment by rroblsgo** [comment]
I’ve reinstalled an it’s all OK.

Thank you very much!
