### ISSUE TITLE
need curl lib with gssapi for pecl_http

### ISSUE THREAD

**Issue by wbovela** [liip/php-osx#235]
I'm installing pecl_http 3.1.1RC1 (by mdref) and PHP7. 

pecl_https gives me the following notice: 
 Notice: http\Client::enqueue(): Could not set option proxy_service_name

This is a known issue (git issue #39) which can be solved by compiling the curl library with GSSAPI support. Is there a compiled PHP7 package for macosx that has this?

Best regards

**Comment by chregu** [comment]
compiled curl with gssapi support. hope that works, just redownload the 7.0 package (7.1 follows soon)

**Comment by wbovela** [comment]
Thanking you copiously!
