### ISSUE TITLE
After installing 7.1 on Mac Sierra 10.12.6 breaks Apache

### ISSUE THREAD

**Issue by RealDevSparky** [liip/php-osx#238]
Installed curl for php71 and Apache stopped working, no services running, and when going to localhost it now fails. (rebooting and restarting Apache did nothing, but apachectl configtest = Status OK)

I had to remove all fills to get Apache to work again.

**Comment by andkerel** [comment]
+1
Exact same thing happened to me - getting a "This site cannot be reached" message on localhost. Also installed 7.1 on macOS 10.12.6.

**Comment by RealDevSparky** [comment]
After upgrading to MacOS High Sierra, PHP has been updated to 7.0, the only thing I had to do was reconfigure the necessary confit and PHP.ini Files as they we reset to the standard.

If you need any help to update these files, just ask 😊

**Comment by niko-kris** [comment]
I have the exact same as andkerel. Also noticed during the install there was a brief prompt for password but the installation continued without allowing me to enter it which may be why /usr/local changes weren't made. Not sure how to get Apache working again.

**Comment by andkerel** [comment]
@niko-kris I had to roll back to get my Apache working again - I followed the uninstall instructions (with a few minor discrepancies as noted). 

@RealDevSparky thanks for the heads up that I'll have to adjust my php.ini/config files when I upgrade to High Sierra - definitely something to keep in mind 🙂

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
