### ISSUE TITLE
Old ssl version

### ISSUE THREAD

**Issue by colingoldberg** [liip/php-osx#240]
Hi,

I successfully installed php5.6 on my Mavericks Mac 10.9.5, but phpinfo output shows the old version of openssl.

ie.
phpinfo()
PHP Version => 5.6.31
...
openssl

OpenSSL support => enabled
OpenSSL Library Version => OpenSSL 0.9.8zg 14 July 2015
OpenSSL Header Version => OpenSSL 0.9.8r 8 Feb 2011
Openssl default config => /System/Library/OpenSSL/openssl.cnf
...

I recently used homebrew to update openssl, which now shows:
# openssl version -a
OpenSSL 1.0.2l  25 May 2017
built on: reproducible build, date unspecified
platform: darwin64-x86_64-cc
options:  bn(64,64) rc4(ptr,int) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: clang -I. -I.. -I../include  -fPIC -fno-common -DOPENSSL_PIC -DZLIB_SHARED -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -arch x86_64 -O3 -DL_ENDIAN -Wall -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/usr/local/etc/openssl"

So how do I get php to use the latest version?

Colin Goldberg

**Comment by togwel** [comment]
Hi Colin,

How was this solved?
I’m heading the same issue...

Like to hear from you.

Regards

**Comment by colingoldberg** [comment]
... I'm trying hard to remember (not my strong point these days) - and shame on me for not posting my solution at the time.

I am sure I did not rebuild php from source. So I must have found a version with the latest openssl version - possibly via homebrew. Have you checked homebrew?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
