### ISSUE TITLE
PHP 5.6 (Old stable) - 10.8 and later Mysql Issues

### ISSUE THREAD

**Issue by fab01** [liip/php-osx#241]
By using PHP 5.6.31 version MySQL doesn't work properly anymore.
For example, when I try to import or export a DB with PhpMyAdmin the connection stay hanging until max execution time is reached.
Same with Drupal VBO.. 
PHP 5.6.19 and 7.1 do not have any issue.
Did anybody have the seme issue?

Ty

**Comment by K15Lmk98** [comment]
I have the same problem. Osx El Capitan
How can I downgrade to version 5.6.27?

Thank you, Claudio

**Comment by fab01** [comment]
Hi Claudio, I tried several ways but, since the package has a really high level of customisation, a manual downgrade is unadvisable. Moreover I had several issues with OpenSSL on version 5.6.19. 
Basically, working on Continuous integration I need an environment 100% efficient and, in order to achieve this I have finally decided to remove completely the liip package and go straight for Brew.

If you have installed mysql using the dmg from mysql.com check this how to to first remove entirely the mysql package (including the mysql widget on System Preferences):
https://devmarketer.io/learn/do-not-install-mysql-macos-sierra-how-to-fix/

Secondly, liip uses the Apache which normally comes with Sierra.
Do not remove it but simply run the Apache provided by Brew.
Here is a cool how to:
https://getgrav.org/blog/macos-sierra-apache-multiple-php-versions

This way you will gain also in terms of organisation. 
If you need some help just let me know.

Have a nice day ;)

**Comment by K15Lmk98** [comment]
Hi fab01,
I see how to proceed.

Thank you, Claudio

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
