### ISSUE TITLE
Install php 5.6 on OS X High Sierra

### ISSUE THREAD

**Issue by jizapata** [liip/php-osx#242]
Hello, i need to instal PHP 5.6 on OS X High Sierra.

I run the command:

curl -s https://php-osx.liip.ch/install.sh | bash -s 5.6

And I get:

****
[WARNING]
Detected macOS High Sierra 10.13. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Password:
tar: Error opening archive: Failed to open '/tmp/packager.tgz'
Start packager (may take some time) using /usr/bin/python2.7
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: can't open file '/usr/local/packager/packager.py': [Errno 2] No such file or directory
Finished.

Help me please!

**Comment by njustice4all** [comment]
+1

**Comment by ssorgente** [comment]
I instead succeeded in installing but... now nothing works! when I write "localhost" on the browser it says that it is not possible to reach the site.... any hints?

**Comment by jurasseck** [comment]
+1

**Comment by weihaixiaoseu** [comment]
+1

**Comment by HoangTrung** [comment]
+1

**Comment by west44** [comment]
+1

**Comment by andsien** [comment]
any updates for this one? Thanks

**Comment by keyboard1988** [comment]
+1 , Have you solve the issue?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
