### ISSUE TITLE
Cannot go back to brew

### ISSUE THREAD

**Issue by tekoyaki** [liip/php-osx#244]
I was using brew with PHP 5.6 before and I tested this (with PHP 5.6 also). I decided to go back to brew and did the [uninstall process](https://php-osx.liip.ch/#uninstall), but still unable to run php56 on brew.

> httpd: Syntax error on line 180 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/opt/php56/libexec/apache2/libphp5.so into server: dlopen(/usr/local/opt/php56/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib\n  Referenced from: /usr/local/opt/php56/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 7.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0

Is there something else I'm missing? I've tried doing brew uninstall, reinstall, cleanup, etc but no luck so far.

On macOS 10.13.2

**Comment by sudewa** [comment]
I have the same issue.
httpd: Syntax error on line 177 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/Cellar/php56/5.6.33_9/libexec/apache2/libphp5.so into server: dlopen(/usr/local/Cellar/php56/5.6.33_9/libexec/apache2/libphp5.so, 10): Library not loaded: /usr/local/opt/apr-util/libexec/lib/libaprutil-1.0.dylib\n  Referenced from: /usr/local/Cellar/php56/5.6.33_9/libexec/apache2/libphp5.so\n  Reason: Incompatible library version: libphp5.so requires version 7.0.0 or later, but libaprutil-1.0.dylib provides version 4.0.0


I am using apache that comes with Mac not the home-brew one.
OS: High Sierra

Thanks.

**Comment by borNfreee** [comment]
anyone managed to fix this issue?

**Comment by chregu** [comment]
The paths mentioned in the error don't point to any file installed by php-osx. So I'm a little bit at loss here.
Did you try reinstall `apr-util`  as well? That seems the culprit in that brew setup

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
