### ISSUE TITLE
Did or could not download package: 7.2-10.10-frontenddev

### ISSUE THREAD

**Issue by luofei2011** [liip/php-osx#247]
```
> curl -s https://php-osx.liip.ch/install.sh | bash -s 7.2

****
[WARNING]
Detected macOS High Sierra 10.13. As this is quite new, there may be issues still. Your mileage may vary.
****
Get packager.tgz
Unpack packager.tgz
Please type in your password, as we want to install this into /usr/local
Start packager (may take some time) using /usr/bin/python2.7
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.2-10.10-frontenddev-latest.dat
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.2-10.10-frontenddev.tar.bz2
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.2-10.10-frontenddev.tar.gz
downloading https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/7.2-10.10-frontenddev.tgz
Did or could not download package: 7.2-10.10-frontenddev
Finished.
```

When i visited the website from chrome. i got:

```
<?xml version="1.0" encoding="UTF-8"?>
<Error><Code>AccessDenied</Code><Message>Access Denied</Message><RequestId>57976D5064061A02</RequestId><HostId>8qd8b0JJeJwi7jrVnYnZvEzq5nFw+EgF5gcpNU/qTL9VjoLRJxSJSpSYQ2lCPsxkEx/iMzn63As=</HostId></Error>


```

**Comment by andyscraven** [comment]
I get the exact same issue!  Anybody found a solution for this?

**Comment by chregu** [comment]
Can you access https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.2-10.10-frontenddev-latest.dat and if yes, what's in it?
I don't know what is happening here, it works totally fine for me and many other people

**Comment by chregu** [comment]
Mhh, that is the wrong URL indeed, But can you download 
 https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.2-10.10/frontenddev/7.2-10.10-frontenddev-7.2.9-20180821-074958.tar.bz2 ?
That's what that content of  https://s3-eu-west-1.amazonaws.com/php-osx.liip.ch/install/7.2-10.10-frontenddev-latest.dat should point to and then try to download

I don't know what's going in, something in /usr/local/packager/packager.py is not redirecting to the correct download file for whatever reason

**Comment by andyscraven** [comment]
Yes that downloads OK.

**Comment by chregu** [comment]
really strange. You can install it also manually. Download that .tgz file, then
```
tar -C /tmp/ -xjf 7.2-10.10-frontenddev-7.2.9-20180821-074958.tar.bz2
sudo mv /tmp/usr/local/php5-7.2.9-20180821-074958 /usr/local/
sudo bash /tmp/pkg/post-install
```
that should work

**Comment by andyscraven** [comment]
Thanks for the help.  I will give it a try.
