### ISSUE TITLE
Make apache (re)start optional

### ISSUE THREAD

**Issue by aurora** [liip/php-osx#250]
Hi,

i very much like your php builds for macOS. The only thing that annoys me a little bit is, that your post-install script actually starts apache, even if it was not running before. I prefer using caddy-server for developments and therefore would love to have a possibility to omit having to stop apache after upgrading php. Which is not really a big deal, but more of a WTF if you forgot about this detail. 

I didn't prepare a pull-request for this, because i am not sure if you would be open for this and if so what in your opinion would be the best way in solving this:

* (re)start apache only if it was running before
* having a configuration flag somewhere to turn this behavior off
* having a flag for the installer that it forwards to the post-install script to prevent apache (re)start

thanks!

**Comment by chregu** [comment]
Sure, I'd be open for a change here. I think the best way would be to just
"(re)start apache only if it was running before"

Still keeps it easy without new options and does nothing unexpected.

**Comment by aurora** [comment]
I am closing this now, thanks for merging!
