### ISSUE TITLE
PHP 7.1 is not available for OS X < 10.10 (Incorrect Version Detected)

### ISSUE THREAD

**Issue by zulhelmi** [liip/php-osx#254]
When trying to install PHP 7.1 on macOS  Mojave 10.14-beta I receive the error shown in the title, so it looks like this is a version detection problem. Is there a way I can force the install, and have it ignore the version?

**Comment by Bjornftw** [comment]
Same issue

**Comment by zhao15** [comment]
Same issue

**Comment by chregu** [comment]
that should be fixed now
