### ISSUE TITLE
PHP 7.2.7 no Xdebug extension

### ISSUE THREAD

**Issue by tflin** [liip/php-osx#255]
The latest PHP 7.2.7 update does not include debug extension. Previously it was said on twitter that 7.2.2 now finally has xdebug support again. Could you help to include it in the new 7.2.7 update?

**Comment by chregu** [comment]
No idea how that happened. Anyway, 7.2.9 is up and with xdebug within again

**Comment by tflin** [comment]
Thanks for the update of 7.2.9. It is with xdebug now.
