### ISSUE TITLE
PHP 7.3.0beta3 no Xdebug extension

### ISSUE THREAD

**Issue by auskov** [liip/php-osx#262]
PHP 7.3.0beta3 no Xdebug extension.
`[bash-3.2$ /usr/local/php5-7.3.0beta3-20180903-112811/bin/php -v
PHP 7.3.0beta3 (cli) (built: Sep  3 2018 11:26:01) ( NTS )
Copyright (c) 1997-2018 The PHP Group
Zend Engine v3.3.0-dev, Copyright (c) 1998-2018 Zend Technologies
    with Zend OPcache v7.3.0beta3, Copyright (c) 1999-2018, by Zend Technologies
bash-3.2$ ls -la /usr/local/php5-7.3.0beta3-20180903-112811/php.d/*debug*
ls: /usr/local/php5-7.3.0beta3-20180903-112811/php.d/*debug*: No such file or directory
bash-3.2$ 
`

**Comment by chregu** [comment]
xdebug is enabled since quite some time
