### ISSUE TITLE
Missing XDebug Extension - PHP 7.3.3

### ISSUE THREAD

**Issue by stancel** [liip/php-osx#268]
First off, thank you for creating and supporting this project. I believe it is the easiest way to add new/different versions of PHP onto Mac OS. I recently upgraded to PHP version 7.3.3 (your current PHP 7.3.x version) and noticed that the Xdebug extension was not compiled and included. I double checked the extensions directory, config files and php_info output, but it was not there.

Would you be willing able to add it into that version? Thanks in advance for your time and help and let me know if there is any way that I can help.

**Comment by chregu** [comment]
xdebug is back

**Comment by stancel** [comment]
Thanks
