### ISSUE TITLE
Can't set error_reporting

### ISSUE THREAD

**Issue by ghost** [liip/php-osx#27]
I've tried set error_reporting in php.ini but it does not take any affect.

Every time php script says that current error_reporting value is 32767.

it's very strange... phpinfo() shows me http://o7.no/A8YGJc

and i'm editing exactly this file. And i can see a lot of extensions is commented there.
but phpinfo() shows me that they are all turned ON.

Looks like php ignore this ini file :(

I tried to see what php does http://o7.no/zPTfpF

and one more thing

$ uname -a
Darwin nnn.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386

maybe i386 is reason ?

**Comment by AknEp** [comment]
great!

why don't you write about this problem at FAQ page? ( http://php-osx.liip.ch/ )
