### ISSUE TITLE
[Help request] how to uninstall?

### ISSUE THREAD

**Issue by erredeco** [liip/php-osx#280]
Hello and sorry for this request; I've installed your software on MacOSX Mojave but I changed my mind and want to remove it. How can I remove every trace of it?

This is the procedure I would want to follow:

`/etc/apache2/httpd.conf` is untouched, so I'll keep it as is

`/etc/apache2/other/+php-osx.conf` -> remove 

```
usr/local/php5
usr/local/php5-7.3.8-20190811-205217
```

-> remove them

`.profile` on my user's folder-> : remove the line export PATH=/usr/local/php5/bin:$PATH

`usr/local/packager`  -> I think it can be removed

Am I missing something? Thank you for your help.

**Comment by chregu** [comment]
No, that should be it.
