### ISSUE TITLE
configuration on OSX (Mountain Lion) Server 

### ISSUE THREAD

**Issue by stringcolor** [liip/php-osx#47]
Thank you for your work on this. Great tool, I do have one remark:
on machines with Server.app instaled, httpd_server_app.conf is the primary configuration file read by Apache (at least on Mountain Lion). Note that it differs from the httpd.conf distributed with Apache. It is specific to Server's Apache configuration, and replaces the desktop Apache configuration in /etc/apache2/httpd.conf. Certain directives are activated when Websites Service is switched on in the Server application; these are bracketed by the "IfDefine WEBSERVICE_ON" blocks.  This file is modified by the server-resident part of the Server application and, in some cases, by webappctl(8). Administrators may make changes directly to this file but it's generally safest to put your changes in separate files and use the Include directive to incorporate them.

Issue is that on a machine with Server instaled, the one line installer does not work. It goes and edits /etc/apache2/httpd.conf after a backup... hence not changing the configuration at all. In other words: there needs to be a check by the installer to see if server is installed or not, and the script needs to edit (and back up) the right httpd configuration file, which is a different file on Server.app-equipped machines.

**Comment by mjmnz** [comment]
@btombaugh - thanks for the contribution. I've use it to fix my MacOS Sierra Server PHP issue. I was wondering what your experience of your 26 Feb 2013 changes has been. Has the system been stable?

**Comment by chregu** [comment]
This project is now deprecated and won't get any more updates (since quite some time, but we made it official now).

The binaries and scripts will still be available for the foreseeable future.

We recommend using a homebrew  based setup for an up-to-date local and native PHP experience.

See https://php-osx.liip.ch/ for more details.
