### ISSUE TITLE
/usr/local/bin/php5: No such file or directory

### ISSUE THREAD

**Issue by nathan-zhu** [liip/php-osx#53]
i update to last version for php5, but get error: httpd: Syntax error on line 118 of /private/etc/apache2/httpd.conf: Cannot load /usr/local/php5/libphp5.so into server: dlopen(/usr/local/php5/libphp5.so, 10): Symbol not found: _environ\n  Referenced from: /usr/local/php5/libphp5.so\n  Expected in: /usr/sbin/httpd\n in /usr/local/php5/libphp5.so

follow the step
What "/usr/local/bin/php5 -v"?

get -bash: /usr/local/bin/php5: No such file or directory

it's very urgent for me, how to fix this problem please help on it, thanks very much.

**Comment by snippet** [comment]
I have a same problem. In terminal ok, php7 runing.
In apache dont working, I cant found file /usr/local/php5/libphp5.so in folder has /usr/local/php5/libphp7.so
