### ISSUE TITLE
pspell support

### ISSUE THREAD

**Issue by GalGavu** [liip/php-osx#91]
Hi,
is there any way to enable pspell so I can use pspell_new? Now I'm getting:
Fatal error: Call to undefined function pspell_new()

**Comment by bilalahmad12** [comment]
Hi,
I am also facing same problem (Fatal error: Call to undefined function pspell_new()) 
have you got solution for that?

**Comment by kaushalmehra21** [comment]
Hi,
I am also facing same problem (Fatal error: Call to undefined function pspell_new())
have you got solution for that?
