### ISSUE TITLE
How do I turn extensions off for when running PHP from the command line?

### ISSUE THREAD

**Issue by josefvn** [liip/php-osx#98]
I'm having issues with `composer update` taking too long, and apparently it's to do with xdebug being enabled for PHP when in the command line.

How do I turn xdebug off for command line PHP, yet leave it enabled for my localhost stuff coming through Apache?

I see that both php -i and phpinfo.php shows the same configuration files loaded?

**Comment by saqueib** [comment]
I want to disabled the `xdebug` for everything but cant find it in `php.ini`

I have tried `php --ini` which gives me loaded file 

```
Configuration File (php.ini) Path: /usr/local/php5/lib
Loaded Configuration File:         /usr/local/php5/lib/php.ini
Scan for additional .ini files in: /usr/local/php5/php.d
Additional .ini files parsed:      /usr/local/php5/php.d/10-extension_dir.ini,
```

I have checked it this file not found `/usr/local/php5/lib/php.ini`
